"""add scientific orchestration tables

Revision ID: 10229a1c5d96
Revises: 
Create Date: 2026-05-26 16:34:03.411288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '10229a1c5d96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dose_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('dose', sa.Float(), nullable=False),
    sa.Column('firing_rate', sa.Float(), nullable=True),
    sa.Column('seizure_score', sa.Float(), nullable=True),
    sa.Column('sync_index', sa.Float(), nullable=True),
    sa.Column('nii', sa.Float(), nullable=True),
    sa.Column('toxicity_score', sa.Float(), nullable=True),
    sa.Column('response_mode', sa.String(length=128), nullable=True),
    sa.Column('biological_state', sa.String(length=128), nullable=True),
    sa.Column('suppression_effect', sa.Float(), nullable=True),
    sa.Column('excitation_effect', sa.Float(), nullable=True),
    sa.Column('stabilization_effect', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run_records.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dose_results_created_at'), 'dose_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_dose_results_run_id'), 'dose_results', ['run_id'], unique=False)
    op.create_index('ix_dose_results_run_id_dose', 'dose_results', ['run_id', 'dose'], unique=False)
    op.create_table('simulation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rq_job_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='simulation_job_status'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_run_id', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('worker_hostname', sa.String(length=255), nullable=True),
    sa.Column('runtime_seconds', sa.Float(), nullable=True),
    sa.Column('queue_latency_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['result_run_id'], ['run_records.run_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_jobs_created_at'), 'simulation_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_result_run_id'), 'simulation_jobs', ['result_run_id'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_rq_job_id'), 'simulation_jobs', ['rq_job_id'], unique=True)
    op.create_index(op.f('ix_simulation_jobs_status'), 'simulation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_worker_hostname'), 'simulation_jobs', ['worker_hostname'], unique=False)
    op.create_index('ix_simulation_jobs_status_created_at', 'simulation_jobs', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_simulation_jobs_status_created_at', table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_status'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_rq_job_id'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_result_run_id'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_created_at'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_worker_hostname'), table_name='simulation_jobs')
    op.drop_table('simulation_jobs')
    op.drop_index('ix_dose_results_run_id_dose', table_name='dose_results')
    op.drop_index(op.f('ix_dose_results_run_id'), table_name='dose_results')
    op.drop_index(op.f('ix_dose_results_created_at'), table_name='dose_results')
    op.drop_table('dose_results')
    # ### end Alembic commands ###
